[build]
  base = "/"
  command = "npm run build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://your-railway-app.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"